CREATE TABLE TIME (
   NOME VARCHAR2(20) NOT NULL,
   ESTADO CHAR(2),
   TIPO VARCHAR2(12),
   SALDO_GOLS NUMBER(4),
   CONSTRAINT PK_TIME PRIMARY KEY(NOME),
   CONSTRAINT CK_TIPO CHECK(UPPER(TIPO) IN ('AMADOR', 'PROFISSIONAL'))
);


CREATE TABLE JOGA (
   TIME1 VARCHAR2(20) NOT NULL,
   TIME2 VARCHAR2(20) NOT NULL,
   CLASSICO CHAR(1),
   CONSTRAINT PK_JOGA PRIMARY KEY(TIME1,TIME2),
   CONSTRAINT FK_TIME1 FOREIGN KEY(TIME1) REFERENCES TIME(NOME) ON DELETE CASCADE,
   CONSTRAINT FK_TIME2 FOREIGN KEY(TIME2) REFERENCES TIME(NOME) ON DELETE CASCADE,
CONSTRAINT CK_TIMES CHECK(UPPER(TIME1)!= UPPER(TIME2)),
CONSTRAINT CK_CLASSICO CHECK(UPPER(CLASSICO) IN('S','N'))
 );

CREATE TABLE PARTIDA (
   TIME1 VARCHAR2(20) NOT NULL,
   TIME2 VARCHAR2(20) NOT NULL,
   DATA DATE NOT NULL,
   PLACAR VARCHAR2(5) DEFAULT '0X0',
   LOCAL VARCHAR2(15),
   CONSTRAINT PK_PARTIDA PRIMARY KEY(TIME1,TIME2,DATA),
   CONSTRAINT FK_TIMES_PARTIDA FOREIGN KEY(TIME1, TIME2) REFERENCES JOGA(TIME1, TIME2) ON DELETE CASCADE,
   CONSTRAINT CK_PLACAR CHECK(REGEXP_LIKE(PLACAR,'[[:digit:]]{1,2}\X[[:digit:]]{1,2}', 'i' ))
);

CREATE TABLE JOGADOR (
   CPF CHAR(14) NOT NULL,
   RG VARCHAR2(20) NOT NULL,
   NOME VARCHAR2(40) NOT NULL,
   DATA_NASC DATE,
   NATURALIDADE VARCHAR2(15),
   TIME VARCHAR2(20) NOT NULL,
   CONSTRAINT PK_JOGADOR PRIMARY KEY(CPF),
   CONSTRAINT FK_TIME_JOGADOR FOREIGN KEY(TIME) REFERENCES TIME(NOME) ON DELETE CASCADE,
   CONSTRAINT UN_JOGADOR UNIQUE(RG, NOME), 
   CONSTRAINT CK_CPF CHECK(REGEXP_LIKE(CPF, '[0-9]{3}\.[0-9]{3}\.[0-9]{3}\-[0-9]{2}'))
);

CREATE TABLE POSICAO_JOGADOR (
   JOGADOR CHAR(14)NOT NULL,
   POSICAO VARCHAR2(10) NOT NULL,
   CONSTRAINT PK_POSICAO_JOGADOR PRIMARY KEY(JOGADOR, POSICAO),
   CONSTRAINT FK_POSICAO_JOGADOR FOREIGN KEY(JOGADOR) REFERENCES JOGADOR(CPF) ON DELETE CASCADE
);

CREATE TABLE DIRETOR (
   TIME VARCHAR2(20) NOT NULL,
   NOME VARCHAR2(20) NOT NULL,
   CONSTRAINT PK_DIRETOR PRIMARY KEY(TIME, NOME),
   CONSTRAINT FK_DIRETOR FOREIGN KEY(TIME) REFERENCES TIME(NOME) ON DELETE CASCADE
);

CREATE TABLE UNIFORME (
   TIME VARCHAR2(20) NOT NULL,
   TIPO CHAR(7) NOT NULL,
   COR_PRINCIPAL VARCHAR2(10),
   CONSTRAINT PK_UNIFORME PRIMARY KEY(TIME, TIPO),
   CONSTRAINT FK_UNIFORME FOREIGN KEY(TIME) REFERENCES TIME(NOME) ON DELETE CASCADE,
   CONSTRAINT CK_UNIFORME CHECK(UPPER(TIPO) IN('TITULAR', 'RESERVA'))
);